name: Escaneo ifconfig

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Escaneo
        run: echo "Instalando escaneo"
      - name: Instalar nmap
        run: sudo apt-get install -y nmap
      - name: Usar nmap
        run: nmap -sV nike.com
